### ISSUE TITLE
API Server metadata needs to track the pod<->IP mapping

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#109]
**Is your feature request related to a problem? Please describe.**
Right now we seem not have the data of IP of the pods

**Describe the solution you'd like**
We want to have this information stored in metadata table

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jmzwcn** [comment]
Currently we could get POD_IP from pods table in status fields.
