### ISSUE TITLE
api-server start crashed

### ISSUE THREAD

**Issue by oowl** [tricorder-observability/Starship#160]
**Describe the bug**
API Server  `pid-collctor` submodule nil pointer crash in the metadata service's PID information collecting
API Server and agents are built from the main line head

**To Reproduce**
Follow [helm-charts instructions](https://github.com/tricorder-observability/Starship#get-started)
to deploy Starship on minikube; you should then see API Server start crashing

**Screenshots**
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/39181969/223590907-a391e1d4-13f8-4066-9d09-6490590d0dc7.png">

**Additional context**

**Comment by nascentcore-eng** [comment]
@owl-ltt Do you have any update on this?

**Comment by oojimmy** [comment]
I have checked agent crash log
```
{"file":"src/agent/deployer/deployer.go:125","function":"StartModuleDeployLoop","level":"fatal","msg":"Failed to read stream from DeplyModule(), error: rpc error: code = Unknown desc = while handling agent grpc request, failed to update node agent state, error: while handling Agent grpc request, failed to save new online agent, error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint","time":"2023-03-09T16:44:45Z"}
```

**Comment by oojimmy** [comment]
and also I have try to add debug code to `pid_collector` module to print debug error msg
![image](https://user-images.githubusercontent.com/123795164/224094745-a6d6ef84-e944-4ea5-88b0-28b279c24689.png)


![image](https://user-images.githubusercontent.com/123795164/224094846-c3bfe69b-3340-43be-bce5-a54e9cf9ee41.png)

**Comment by oojimmy** [comment]
So this panic was caused by grpc stream closing, but our code has not handled this error.
