### ISSUE TITLE
For UI code base, `yarn run dev` should listen on 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#232]
**Describe what should be done**
Right now `yarn run dev` in UI listens on localhost:8000, we want to change to 0.0.0.0 so that connections from Internet can reach the server.

**Describe alternatives considered**
None

**Additional context**
None

**Comment by zhoujie16** [comment]
The default usage of the 'run dev' command is to run on the '0.0.0.0' IP. If you need to specify an IP, you can use the 'run dev --host 0.0.0.0' command.
