### ISSUE TITLE
API Server has lots of slow query into SQLite

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#28]
![image](https://user-images.githubusercontent.com/112656580/213738305-c3f70d4b-a8b7-495d-af10-4b672d07fb57.png)

Just deploy Starship and check API server's log

**Comment by tricorder-eng** [comment]
We have chatted yesterday, and decided that we'd want to create a channel between API server's http component and gRPC component.
- When http component receives user requests of any kind
- Send a message over the channel
- The gRPC component wait on the channel, and perform a full query over the sqlite db about (to be deployed module, and to be underployed, and to be deleted etc)
