### ISSUE TITLE
Error happen when ./devops/release/build_and_push_images.sh run

### ISSUE THREAD

**Issue by jmzwcn** [tricorder-observability/Starship#4]
Error happen when ./devops/release/build_and_push_images.sh run.

This will result in mgmt-ui's image tag couldn't been made and push correctly.

https://github.com/tricorder-observability/helm-charts/pull/88

**Comment by jmzwcn** [comment]
![screenshot-20230215-175457](https://user-images.githubusercontent.com/11627425/218997002-52c36da8-0488-4fe9-adf2-5ddcdc5e1550.png)

**Comment by nascentcore-eng** [comment]
How to reproduce?

I haven't run int this issue.

**Comment by jmzwcn** [comment]
> How to reproduce?
> 
> I haven't run int this issue.

Directly run ./devops/release/build_and_push_images.sh, this error will happen. Likely need to investigate this shell file's dependencies issue.

**Comment by nascentcore-eng** [comment]
The issue is that yarn is not installed on the host.
