### ISSUE TITLE
Revamp API Server module management logic

### ISSUE THREAD

**Issue by JaredTan95** [tricorder-observability/Starship#45]
**Describe the bug**
https://github.com/tricorder-observability/starship/blob/852be118c353b2e72ac609ee64a04afbd15f611f/src/api-server/grpc/deployer.go#L114

deployer will update the `module`'s status when `one of agent` deploy success. It causes the left agents will not receive the deploy request.

**Expected behavior**
All of the agents receive module deploy requests.

**Screenshots**

**Additional context**

**Sub tasks**
- [x] #124

**Comment by nascentcore-eng** [comment]
https://tricorder.feishu.cn/wiki/wikcnVXHjFF1zHEqProyQRnHb0c

We have summarized the desired workflow in this doc.
@JaredTan95 @jmzwcn @zh9310

**Comment by feuyeux** [comment]
It's would be better to setup a task queue machenism to solve both with the issue [150](https://github.com/tricorder-observability/Starship/issues/150)

**Comment by oojimmy** [comment]
API-server refactor have done in https://github.com/tricorder-observability/Starship/pulls?q=is%3Apr+is%3Aclosed+author%3Aowl-ltt+refactor%28api-server%29
