### ISSUE TITLE
Add license headers to all source files

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#48]
**Context**
Right now, we use AGPL license, but source files have no license header.

**Objective**
All source files should have license header

**Proposed solution**
[Skywalking-eyes](https://github.com/apache/skywalking-eyes) could be used

First automatically add license header on all source files.
And then add [fossa check](https://app.fossa.com/projects/import)

**Comment by JaredTan95** [comment]
.licenserc.yaml defines : https://github.com/apache/skywalking-eyes/blob/main/.licenserc.yaml
