### ISSUE TITLE
Grafana dashboard not created for ddos_event module using starship CLI

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#57]
**Describe the bug**
TBA

**To Reproduce**
TBA

**Expected behavior**
TBA

**Screenshots**
![3cb94259-bcf6-45c8-8d58-428147ed37a9](https://user-images.githubusercontent.com/112656580/219988913-68e20017-474d-498e-bfdb-4d49d6ce9722.jpeg)

**Additional context**

**Comment by nascentcore-eng** [comment]
This is a real issue, I now cannot create dashboard on grafana:

![image](https://user-images.githubusercontent.com/112656580/220383502-06396045-6488-4f33-988a-69c88b56d392.png)

**Comment by zh9310** [comment]
This error is that the tricorde.db file is not initialized, and the tricrode.db file of another cluster is used

**Comment by zh9310** [comment]
This place solves this problem https://github.com/tricorder-observability/starship/issues/81
