### ISSUE TITLE
API Server's container info collector has a broken logic

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#60]
**Describe the bug**
The watcher would write container info object directly over gRPC streaming channel to the agent.
But when the gRPC streaming channel is closed, there is no way to inform the watcher to write a different agent.
Or make it stop.

**To Reproduce**
Just delete an agent, the API Server's previously-created watcher will continue to run, but always produces gRPC channel failure.

**Expected behavior**
API Server should gracefully stops watcher, and waiting for the new watcher to be created for the restarted agent.

**Screenshots**
![image](https://user-images.githubusercontent.com/112656580/220047233-45634623-56d3-422e-b838-db44780b4055.png)

**Additional context**
None

**Comment by nascentcore-eng** [comment]
Add the commit that fixes this bug and close this issue.

**Comment by jmzwcn** [comment]
https://github.com/tricorder-observability/starship/commit/3c63b6293b8472da3802ea8224117692ebdbc26f
