### ISSUE TITLE
It is recommended that the dev image have a cn repo

### ISSUE THREAD

**Issue by yaoyaoio** [tricorder-observability/Starship#72]
**Is your feature request related to a problem? Please describe.**
I was running `./devops/dev_image/run.sh`, It takes a long time to wait.
I think Increase china download speed
**Describe the solution you'd like**
I think need `cn-hub.xx.com/tricorder/dev_image:{version}` replace `public.ecr.aws/tricorder/dev_image:202301250648`
**Describe alternatives you've considered**

**Additional context**

**Comment by nascentcore-eng** [comment]
(Kuririn is one of my favorite Dragon Ball characters)
We'll be moving image hosting from aws ecr-public to github and aliyun
Stay tuned

**Comment by JaredTan95** [comment]
duplicated with https://github.com/tricorder-observability/starship/issues/44
