### ISSUE TITLE
Api Server remove Grafana Api Keys and create grafana api key

### ISSUE THREAD

**Issue by zh9310** [tricorder-observability/Starship#81]
Api Server remove grafana key and create grafana key

**Comment by zh9310** [comment]
https://grafana.com/docs/grafana/latest/developers/http_api/auth/#delete-api-key

**Comment by zh9310** [comment]
api server start check has grafana api key, if has api key remove and create new api key.

**Comment by nascentcore-eng** [comment]
This also has the benefit of no more gorm management of SQLite record for the cached credential

Basically we now make API Server managing grafana largely stateless

And state is the bane of any program
