### ISSUE TITLE
Add api-server document

### ISSUE THREAD

**Issue by zh9310** [tricorder-observability/Starship#9]
Provide http api document.

This doc is for the frontend engineer, so that they can have an easier time integrate the frontend with the API server.

First write in feishu doc, and then move to markdown

**Comment by oojimmy** [comment]
Have we considered OpenAPI spec for this project? https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md, It will have some API spec generator tools for golang, we can use it generate API spec doc, and distribute its doc spec in this GitHub code base.

**Comment by oojimmy** [comment]
And OpenAPi spec has some beautiful view tools, like this https://editor.swagger.io/

**Comment by nascentcore-eng** [comment]
Duplicate of https://github.com/tricorder-observability/starship/issues/43
